# @package _global_
defaults:
  - libero_pro_spatial_gr00t_grpo_task
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

runner:
  logger:
    project_name: libero_pro_spatial_gr00t
    experiment_name: libero_pro_spatial_gr00t_grpo_task_large_set
