# @package _global_
defaults:
  - /libero_goal_grpo_openvlaoft@_global_
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

runner:
  logger:
    log_path: /PROJECT_ROOT/archive/checkpoints/logs
    project_name: libero_pro_goal_task_openvlaoft
    experiment_name: libero_pro_goal_openvlaoft_grpo_task_large_set
    logger_backends:
      - wandb
    num_eval_videos: 8
  max_epochs: 60
  val_check_interval: 1
  save_interval: 10

algorithm:
  kl_penalty_type: low_var_kl
  group_size: 8
  rollout_epoch: 1
  eval_rollout_epoch: 6
  update_epoch: 2
  kl_beta: 0.0
  clip_ratio_high: 0.2
  log_max_groups: 8

env:
  enable_offload: false
  train:
    libero_variant: pro
    total_num_envs: 64
    reward_coef: ${algorithm.reward_coef}
    perturbation_suffix: task
  eval:
    libero_variant: pro
    total_num_envs: 80
    perturbation_suffix: task
    video_cfg:
      save_video: False

rollout:
  model:
    model_path: /PROJECT_ROOT/models/Openvla-oft-SFT-libero-goal-traj1

actor:
  micro_batch_size: 32
  global_batch_size: 1024
  model:
    model_path: /PROJECT_ROOT/models/Openvla-oft-SFT-libero-goal-traj1
    unnorm_key: libero_goal_no_noops
  optim:
    lr: 1e-5
