# @package _global_
defaults:
  - libero_pro_goal_pi05_her_dual_task_large_set
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

runner:
  logger:
    experiment_name: libero_pro_goal_pi05_her_dual_task_large_set_force_all_groups

algorithm:
  her_dual_force_all_groups: true
