# @package _global_
defaults:
  - libero_pro_goal_pi05_grpo_task
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

runner:
  logger:
    experiment_name: libero_pro_goal_pi05_her_task

algorithm:
  update_epoch: 4
  modification_batch_mode: inplace
  modification_type: her
  her_selection: threshold
  her_low_threshold: 0.8
  her_high_threshold: 1.0
  her_anchor_from_success: true
  her_anchor_reward_one: true
  her_endpoint: http://VLM_ENDPOINT_HOST:PORT/v1
  her_endpoint_file: /PROJECT_ROOT/her_router_endpoint.txt
  her_model: Qwen/Qwen3-VL-235B-A22B-Thinking-FP8
  her_video_mode: frames
  her_prompt_version: v7
  her_reward_eval_prompt_version: 6
  her_prompt_debug_log_n: 2
  her_num_samples: 1
  her_temperature: 0.8
  her_reward_eval_num_samples: 1 # 1: single-sample, >1: majority voting
  her_reward_eval_vote_temperature: 0.6 # only used for majority voting

actor:
  her: {}
