# @package _global_
defaults:
  - libero_pro_object_openvlaoft_her_task_large_set
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

runner:
  logger:
    experiment_name: libero_pro_object_openvlaoft_group_ranking_task_large_set

algorithm:
  modification_type: group_ranking
  ranking_max_frames_per_traj: 8
  filter_rewards: false
