# @package _global_
defaults:
  - libero_pro_10_pi05_grpo_task_large_set
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

runner:
  logger:
    project_name: libero_pro_10_task
    experiment_name: libero_pro_10_pi05_grpo_task_huge
  max_epochs: 100
  save_interval: 10

algorithm:
  rollout_epoch: 8
  update_epoch: 4

actor:
  micro_batch_size: 128
  global_batch_size: 2048
  optim:
    lr: 5e-6
