# @package _global_
defaults:
  - /libero_10_ppo_openpi_pi05@_global_
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

runner:
  logger:
    log_path: /PROJECT_ROOT/logs
    project_name: libero_pro_10_task
    experiment_name: libero_pro_10_pi05_ppo_task
    logger_backends:
      - wandb
    num_eval_videos: 8
  max_epochs: 500
  val_check_interval: 1
  save_interval: 10

algorithm:
  rollout_epoch: 1
  eval_rollout_epoch: 6

env:
  enable_offload: false
  train:
    libero_variant: pro
    total_num_envs: 32
    reward_coef: ${algorithm.reward_coef}
    perturbation_suffix: task
  eval:
    libero_variant: pro
    total_num_envs: 80
    perturbation_suffix: task
    video_cfg:
      save_video: False

rollout:
  unnorm_key: null
  model:
    model_path: /PROJECT_ROOT/models/RLinf-Pi05-LIBERO-SFT

actor:
  micro_batch_size: 32
  global_batch_size: 512
  model:
    model_path: /PROJECT_ROOT/models/RLinf-Pi05-LIBERO-SFT
  optim:
    lr: 2e-6
