# @package _global_
defaults:
  - libero_pro_10_openvlaoft_her_task_large_set
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

runner:
  logger:
    experiment_name: libero_pro_10_openvlaoft_her_dual_task_large_set

algorithm:
  update_epoch: 2
  her_loss_weight: 0.006
  her_loss_clip: 0.25
  her_skip_same_instruction: true
  her_anchor_from_success: false
  her_dual_force_all_groups: false

actor:
  her_dual: {}
